version: "3"
services:
  app:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=http://localhost:3001
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:80"
    restart: on-failure
    container_name: app
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: on-failure
    container_name: api
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - NODE_SERVER_PORT=3001
      - APP_URL=http://localhost:3000
